before_script:
    - angr-test sync hard

### local
angrop:
    script: "angr-test angrop"
    tags: [angr]

lint:
    script: "angr-test lint"
    tags: [angr]

### first level
rex:
    script: "angr-test rex"
    tags: [angr]

patcherex:
    script: "angr-test patcherex"
    tags: [angr]
